[package]
name = "meteo"
version = "0.1.0"
authors = ["Samuel Dolt <samuel@dolt.ch>"]

[dependencies]
slog = "1.3.2"
slog-term = "1.3.3"
regex = "0.1.80"
chrono = "0.2.25"
lazy_static = "0.2.2"

[dependencies.gtk]
version = "0.1.1"
features = ["v3_10"]

[features]
